# need super user permissions to work with Docker
sudo: required
services:
  - docker

# build docker image and tag it so travis can use it
before_install:
  - docker build -t surfero/docker-react -f Dockerfile.dev .

# contains all commands needed to run test suite
script:
  - docker run -e CI=true surfero/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-738513091099"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
